### ISSUE TITLE
Better behaviour when cancelling g-flite

### ISSUE THREAD

**Issue by kubkon** [golemfactory/g-flite#17]
Currently, when the user triggers a termination event (CtrlC), the app sends a message to the Golem node to delete the Task from existence which technically is not the correct behaviour for two main reasons:
1) cancelling a task should *not* remove it from history
2) cancelling an on-going task should remove funds lock *only* from subtasks which are still awaiting computation

**Comment by kubkon** [comment]
cc @lukasz-glen

**Comment by wp31** [comment]
Does cancelling a task (i.e. CtrlC) cause the requestor to be banned from nodes?  Have noticed problems doing tasks after cancelling a task.

**Comment by kubkon** [comment]
@wp31 hmm, I’m not sure. I’ll investigate and report my findings back in this thread.

**Comment by wp31** [comment]
Thanks.  I've been having issues on the testnet as a requestor and I'm trying to figure out why.

**Comment by kubkon** [comment]
> Thanks. I've been having issues on the testnet as a requestor and I'm trying to figure out why.

@wp31 so I've now reverted the behaviour when cancelling `g-flite` from deleting the task back to simply aborting it. Could you check if that fixes your issues on the testnet as a requestor? You can get the precompiled binary with the changes included [here](https://github.com/golemfactory/g-flite/releases/tag/0.3.2-rc).
